server:
  port: 9094


spring:

  data:
    mongodb:
      host: localhost
      port: 27017
      database: hrmEmployeeDB
      username: defaultUSer
      password: bilge!*123
  rabbitmq:
    host: localhost
    port: 5672
    username: java11
    password: 123

jwt:
  secretkey: "Yoklr8?8h8biDrOtiS_iT_opheQlKE@l3WEVL_!a4E6e#r*Seb+phEwO$7arURaZ"
  issuer: "java11Bilgeadam"
  audience: "bilgeadam"


rabbitmq:
  queue-expense-queue: expense-queue
  queue-permission-queue: permission-queue
  queue-advance-queue: advance-queue