server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/hrmUserDB
  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: java11
    password: 123


jwt:
  secretkey: "Yoklr8?8h8biDrOtiS_iT_opheQlKE@l3WEVL_!a4E6e#r*Seb+phEwO$7arURaZ"
  issuer: "java11Bilgeadam"
  audience: "bilgeadam"

rabbitmq:
  exchange-user: user-exchange
  register-key: register-key
  queue-register: register-queue
  register-mail-key: register-mail-key
  register-mail-queue: register-mail-queue
  password-reset-mail-key: password-reset-mail-key
  password-reset-mail-queue: password-reset-mail-queue
